### ISSUE TITLE
USB Midi support for iOS

### ISSUE THREAD

**Issue by hsallander** [kshoji/Unity-MIDI-Plugin-supports#2]
Hi! Any plans to add USB Midi support for iOS? I’m guessing it would be fairly easy since you’ve already hooked into the iOS Core Midi to support BLE? Or is there some other reason for not supporting usb midi on iOS?

**Comment by tgrayston** [comment]
In my testing USB MIDI does in fact work on iOS. Not sure why it's not listed as supported.

**Comment by kshoji** [comment]
I bought lightning USB OTG cable last week, and tested with iPod touch 7th gen.
And confirmed the USB MIDI devices worked with the cable, without changing any source codes.

I'll update document about USB MIDI support.

**Comment by kshoji** [comment]
I updated the documents at #3.

**Comment by hsallander** [comment]
That's great news. Thanks!

**Comment by hsallander** [comment]
Doing some tests now I'm still unable to get it to work on iOS or Mac at all. With both BLE and USB Midi i'm able to connect to the Midi device, but whatever command I send nothing reaches the device. I've tried hooking it up to Midi Monitor to see the exacts commands being sent from the plugin, but even though the plugin says it's connected to the Midi Monitor no commands I send from the plugin show up. Are you sure it really works on the latest macOS and latest iOS? 

@tgrayston @kshoji Are there any tricks to getting it to work? I'm using macOS 13.1, and building for iOS 16. Installing the plugin in a fresh and empty Unity 2021.3.16f1 project.
