### ISSUE TITLE
Unity frozen on runtime in Editor

### ISSUE THREAD

**Issue by randomknobs** [kshoji/Unity-MIDI-Plugin-supports#26]
Hello, imported asset (version 1.5) today but unity gets stuck when i run sample scene in editor Mac OS , IOS, WebGL..tried everything.  After force quitting few times unity (latest 2022) started to crash on runtime.Tried to install a version of unity stated in one of the reviews (2021.1.28f1). Stuck again. Force quit and same crashing story.. Am i doing something wrong? Can not make it work at all. I am on Catalina..    
Maybe it possible to get older version of the plugin with Unity version information, so it all works? Please help

**Comment by randomknobs** [comment]
![Uploading Screenshot 2024-06-16 at 18.21.01.png…]()

**Comment by randomknobs** [comment]
tried 2022.3.33f1 ...stuck again, importing assets...seems to me its Catalina issue.... probably need older version to use with Catalina... true or false?

**Comment by kshoji** [comment]
I develop using macOS Ventura and Monterey, and have had no freezes.

Please take the Unity editor log after Unity frozen.
And send it the email to my email (0x0badc0de@gmail.com).
```
~/Library/Logs/Unity/Editor.log
```

I can share older versions as well. Which version would you want?
If I share the package on github, people who haven't purchased it will be able to download it, so I would like to respond by email.

**Comment by kshoji** [comment]
If deleting this directory fixes the situation, the problem is likely with the macOS plugin implements.
```
Assets/MIDI/Plugins/macOS/MIDIPlugin.bundle
```

**Comment by randomknobs** [comment]
deleting it made it run but i did not see any gui. will email you now with crash log. also there was some gui problem i think , had this message in console while it was stuck but
<img width="746" alt="Screenshot 2024-06-17 at 10 36 40" src="https://github.com/kshoji/Unity-MIDI-Plugin-supports/assets/75247153/bf67f7e8-f597-4098-ae57-90728dfaa279">

**Comment by kshoji** [comment]
It seems there is a GUID collision. I've never had this happen with a Scene file before...
Would it be possible to resolve the issue by overwriting `Assets/MIDI/Samples/Scenes/MidiSampleScene.unity.meta` with the attached file?
(Please extract the zip file as github does not support the .meta format.)
[MidiSampleScene.unity.meta.zip](https://github.com/user-attachments/files/15861307/MidiSampleScene.unity.meta.zip)

I also checked the Editor.log you provided, but I couldn't find any clues that might indicate an error.

**Comment by randomknobs** [comment]
wow thanks a lot , will try it now

**Comment by randomknobs** [comment]
unfortunately replacing file did not work, frozen on "importing assets" again , although the console message was gone...
here is the log:

Unity Editor version:    2022.3.33f1 (b2c853adf198)
Branch:                  2022.3/staging
Build type:              Release
Batch mode:              NO
macOS version:           Version 10.15.7 (Build 19H2026)
Darwin version:          19.6.0
Architecture:            x86_64
Running under Rosetta:   NO
Available memory:        16384 MB
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Successfully connected to the License Client on channel: "LicenseClient-hypnaton" at "2024-06-17T04:57:07.077011Z"
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 1.15.4+eee609c
  Session Id:              5acc91a4ac404a188a99c9f11ffa5e61
  Correlation Id:          84e8693cd2e3f7eee43b537f0f572bfa
  External correlation Id: 743433008489030891
  Machine Id:              im60oatEutvQyGajFxTRH5ZsvD8=
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-hypnaton" (connect: 0.00s, validation: 0.01s, handshake: 1.27s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-hypnaton-notifications" at "2024-06-17T04:57:08.362473Z"
[Licensing::Client] Successfully updated the access token
[Licensing::Module] Successfully updated the access token 02WKVtX-Mw...
[Licensing::Client] Successfully updated license
[Licensing::Client] Successfully resolved entitlements
[Licensing::Module] Serial number assigned to: "F4-TBEQ-YQEF-MAAZ-7V48-XXXX"
Pro License: NO
Launching external process: /Applications/Unity/Hub/Editor/2022.3.33f1/Unity.app/Contents/Resources/PackageManager/Server/UnityPackageManager

COMMAND LINE ARGUMENTS:
/Applications/Unity/Hub/Editor/2022.3.33f1/Unity.app/Contents/MacOS/Unity
-projectpath
/Users/hypnaton/Desktop/OKOK
-useHub
-hubIPC
-cloudEnvironment
production
-licensingIpc
LicenseClient-hypnaton
-hubSessionId
aa4a17a0-9239-48d0-9561-b7cd1a5ce329
-accessToken
02WKVtX-MwAL0StTZ20WWyMvZev9tixc0oEqx_eRTWk005f
Successfully changed project path to: /Users/hypnaton/Desktop/OKOK
/Users/hypnaton/Desktop/OKOK
[Package Manager] Server::Kill -- Server was shutdown

**Comment by randomknobs** [comment]
If you can email me back previous versions i would check them... otherwise will have to upgrade i guess..

**Comment by randomknobs** [comment]
guess its catalina issue..will have to install new system

**Comment by kshoji** [comment]
The macOS plugin's build target was specified as 12.3(macOS Monterey).
Change this line to lower version (like 10.13) and rebuild, this issue may be fixed.
https://github.com/kshoji/Unity-MIDI-Plugin-OSX/blob/main/MIDIPlugin.xcodeproj/project.pbxproj#L239

I've sent the rebuilt macOS plugin on the email. Please try it.

**Comment by randomknobs** [comment]
yes that worked, thank big time! great support!!!!! Arigatooooo!

**Comment by kshoji** [comment]
Thanks for confirming the fix. I'll update the asset soon!
